-- 코드를 입력하세요
SELECT A.AUTHOR_ID
      ,B.AUTHOR_NAME
      ,A.CATEGORY
      ,SUM(C.SALES*A.PRICE) AS TOTAL_SALES
  FROM BOOK A
      ,AUTHOR B
      ,BOOK_SALES C
WHERE A.AUTHOR_ID = B.AUTHOR_ID
  AND A.BOOK_ID   = C.BOOK_ID
  --AND TO_CHAR(SALES_DATE,'YYYYMM') = '202201'
  AND EXTRACT(YEAR FROM SALES_DATE) = '2022'
  AND EXTRACT(MONTH FROM SALES_DATE) = '01'
GROUP BY A.AUTHOR_ID,  B.AUTHOR_NAME, A.CATEGORY
ORDER BY A.AUTHOR_ID asc, A.CATEGORY DESC
;