-- 코드를 작성해주세요
WITH FIRST_GEN AS (
    SELECT ID
      FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SECOND_GEN AS(
    SELECT A.ID, A.PARENT_ID
      FROM ECOLI_DATA A
          ,FIRST_GEN B
    WHERE A.PARENT_ID = B.ID
)
SELECT C.ID
  FROM ECOLI_DATA C
      ,SECOND_GEN D
WHERE C.PARENT_ID = D.ID
ORDER BY C.ID
;