-- 코드를 입력하세요
SELECT A.CAR_ID
      ,A.CAR_TYPE
      ,ROUND(A.DAILY_FEE*30*(1-(DISCOUNT_RATE/100)),0) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR A
      JOIN(
            SELECT *
              FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE DURATION_TYPE = '30일 이상'
      ) T ON A.CAR_TYPE = T.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단','SUV')
  AND A.CAR_ID NOT IN (
                    SELECT X.CAR_ID
                      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY X
                    WHERE TO_CHAR(X.END_DATE,'yyyymmdd') >= '20221101'
                      AND TO_CHAR(X.START_DATE,'yyyymmdd') <= '20221130'
)
group by A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE*30*(1-(DISCOUNT_RATE/100)),0)
Having ROUND(A.DAILY_FEE*30*(1-(DISCOUNT_RATE/100)),0) >= 500000
   AND ROUND(A.DAILY_FEE*30*(1-(DISCOUNT_RATE/100)),0) < 2000000
 ORDER BY FEE DESC, A.CAR_TYPE,A.CAR_ID DESC
 ;
