-- 코드를 입력하세요
SELECT A.CAR_ID
      ,A.CAR_TYPE
      ,ROUND(A.DAILY_FEE*30*(100-B.DISCOUNT_RATE)/100,0) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR A
    JOIN(
        SELECT *
          FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE = '30일 이상') B ON A.CAR_TYPE = B.CAR_TYPE
WHERE A.CAR_TYPE IN ('세단', 'SUV')
  AND A.CAR_ID NOT IN(
    SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE >='2022-11-01'
      AND START_DATE <= '2022-11-30'
  )
 GROUP BY A.CAR_ID,A.CAR_TYPE 
 HAVING FEE BETWEEN 500000 AND 2000000
 ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC
 ;