-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) AS YEAR
      ,MONTH(B.SALES_DATE) AS MONTH
      ,A.GENDER
      ,COUNT(DISTINCT B.USER_ID) AS USERS
  FROM USER_INFO A
      ,ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID
  AND A.GENDER IN (0,1)
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER
ORDER BY YEAR, MONTH, A.GENDER
;