-- 코드를 입력하세요
SELECT A.PRODUCT_ID
      ,A.PRODUCT_NAME
      ,A.PRODUCT_CD
      ,A.CATEGORY
      ,A.PRICE
  FROM FOOD_PRODUCT A
WHERE PRICE = (SELECT MAX(X.PRICE)
                 FROM FOOD_PRODUCT X
              )
;