-- 코드를 입력하세요
SELECT CAR_ID
      ,CASE WHEN CAR_ID IN (SELECT X.CAR_ID
                           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY X
                         WHERE '2022-10-16' BETWEEN X.START_DATE AND X.END_DATE)
            THEN '대여중'
            ELSE '대여 가능'
            END AS AVAILABILITY
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC
;