-- 코드를 입력하세요
SELECT A.PRODUCT_ID
      ,A.PRODUCT_NAME
      ,SUM(A.PRICE*B.AMOUNT) AS TOTAL_SALES
  from FOOD_PRODUCT A
      ,FOOD_ORDER B
where A.PRODUCT_ID = B.PRODUCT_ID
  and YEAR(B.PRODUCE_DATE) = '2022'
  and MONTH(B.PRODUCE_DATE) = '05'
GROUP BY A.PRODUCT_ID
      ,A.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID