-- 코드를 입력하세요
SELECT A.PRODUCT_ID
      ,B.PRODUCT_NAME
      ,SUM(B.PRICE*A.AMOUNT) AS TOTAL_SALES
  FROM FOOD_ORDER A
      ,FOOD_PRODUCT B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
  -- AND TO_CHAR(A.PRODUCE_DATE,'YYYYMM') = '202205'
  AND EXTRACT(YEAR FROM A.PRODUCE_DATE) = '2022'
  AND EXTRACT(MONTH FROM A.PRODUCE_DATE) = '05'
GROUP BY A.PRODUCT_ID,B.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID
;