-- 코드를 입력하세요
SELECT HOUR
      ,COUNT(O.DATETIME) AS COUNT
 FROM
 (
    SELECT ROW_NUMBER() OVER (ORDER BY ANIMAL_ID ASC) - 1 AS HOUR
       FROM ANIMAL_OUTS
     LIMIT 24
 )A LEFT OUTER JOIN ANIMAL_OUTS O
 ON A.HOUR = HOUR(O.DATETIME)
 GROUP BY HOUR
 ORDER BY HOUR;