-- 코드를 입력하세요
SELECT A.PT_NAME
      ,A.PT_NO
      ,A.GEND_CD
      ,A.AGE
      ,IFNULL(A.TLNO,'NONE') AS TLNO
  FROM PATIENT A
WHERE A.AGE <= 12
  AND GEND_CD = 'W'
ORDER BY A.AGE DESC, A.PT_NAME ASC
;
  