-- 코드를 입력하세요
SELECT A.MEMBER_ID
      ,A.MEMBER_NAME
      ,A.GENDER
      ,TO_CHAR(A.DATE_OF_BIRTH,'YYYY-MM-DD') AS DATE_OF_BIRTH
  FROM MEMBER_PROFILE A
WHERE EXTRACT(MONTH FROM A.DATE_OF_BIRTH) = 3
  AND A.GENDER = 'W'
  AND TLNO IS NOT NULL
ORDER BY A.MEMBER_ID
;