-- 코드를 입력하세요
SELECT A.MEMBER_ID
      ,A.MEMBER_NAME
      ,A.GENDER
      ,TO_CHAR(DATE_OF_BIRTH,'YYYY-MM-DD') AS DATE_OF_BIRTH
  FROM MEMBER_PROFILE A
WHERE SUBSTR(TO_CHAR(DATE_OF_BIRTH,'YYYYMMDD'),5,2) = '03'
  AND TLNO IS NOT NULL
  AND GENDER = 'W'
 ORDER BY A.MEMBER_ID
  ;