-- 코드를 입력하세요
SELECT MONTH(A.START_DATE) AS MONTH
      , A.CAR_ID
      , COUNT(A.HISTORY_ID) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE A.CAR_ID IN  ( SELECT X.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY X
        WHERE START_DATE >= '2022-08-01'
          AND START_DATE <= '2022-10-31'
        GROUP BY X.CAR_ID
        HAVING COUNT(X.HISTORY_ID) >= 5
       )
   AND START_DATE >= '2022-08-01'
   AND START_DATE <= '2022-10-31'
GROUP BY MONTH(A.START_DATE), A.CAR_ID
HAVING COUNT(1) <> 0
ORDER BY MONTH ASC, A.CAR_ID DESC
;