-- 코드를 입력하세요
SELECT EXTRACT(MONTH FROM A.START_DATE) AS MONTH
      , A.CAR_ID
      , COUNT(1) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE A.CAR_ID IN  ( SELECT X.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY X
        WHERE EXTRACT(MONTH FROM X.START_DATE) >= 8
          AND EXTRACT(MONTH FROM X.START_DATE) <= 10
        GROUP BY X.CAR_ID
        HAVING COUNT(X.CAR_ID) >= 5
       )
   AND EXTRACT(MONTH FROM A.START_DATE) >= 8
   AND EXTRACT(MONTH FROM A.START_DATE) <= 10
GROUP BY EXTRACT(MONTH FROM A.START_DATE), A.CAR_ID
HAVING COUNT(1) != 0
ORDER BY MONTH ASC, A.CAR_ID DESC
;