-- 코드를 입력하세요
SELECT EXTRACT(MONTH FROM START_DATE) as MONTH
      ,CAR_ID
      ,COUNT(1) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE,'YYYYMM') >= '202208'
  AND TO_CHAR(START_DATE,'YYYYMM') <= '202210'
  AND CAR_ID IN (SELECT X.CAR_ID
                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY X
                 WHERE TO_CHAR(X.START_DATE,'YYYYMM') >= '202208'
                   AND TO_CHAR(X.START_DATE,'YYYYMM') <= '202210'
                 GROUP BY CAR_ID
                 HAVING COUNT(1) >= 5
                )
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
HAVING COUNT(1) != 0
ORDER BY MONTH, CAR_ID DESC