-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID
  from CAR_RENTAL_COMPANY_CAR A
      ,CAR_RENTAL_COMPANY_RENTAL_HISTORY B
where A.CAR_ID = B.CAR_ID
  and A.CAR_TYPE = '세단'
  and MONTH(START_DATE) = 10
order by A.CAR_ID DESC
;
